<!DOCTYPE html>
<html lang="ko">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>건강보험 요양급여 청구 위임장 — {{ $prescription->rx_number }}</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: '맑은 고딕', 'Malgun Gothic', '나눔고딕', sans-serif; font-size: 13px; color: #111; background: #fff; }

  .page { width: 210mm; min-height: 297mm; margin: 0 auto; padding: 20mm 20mm 18mm; }

  /* 제목 */
  .doc-title {
    text-align: center; font-size: 20px; font-weight: 800; letter-spacing: 4px;
    border-top: 3px solid #111; border-bottom: 3px solid #111;
    padding: 12px 0; margin-bottom: 18px;
  }
  .doc-sub { text-align: center; font-size: 11px; color: #555; margin-bottom: 26px; letter-spacing: 1px; }

  /* 섹션 */
  .section { margin-bottom: 18px; }
  .section-title {
    font-size: 13px; font-weight: 700; background: #f0f0f0;
    padding: 5px 10px; border-left: 4px solid #333; margin-bottom: 8px;
  }

  /* 정보 테이블 */
  table.info-tbl { width: 100%; border-collapse: collapse; font-size: 12.5px; }
  table.info-tbl td { padding: 5px 8px; border: 1px solid #bbb; vertical-align: middle; }
  table.info-tbl td.label { width: 28%; background: #fafafa; font-weight: 600; white-space: nowrap; }

  /* 위임 내용 박스 */
  .content-box {
    border: 2px solid #333; border-radius: 2px;
    padding: 16px 18px; font-size: 13px; line-height: 2; text-align: justify;
  }
  .content-box b { border-bottom: 1px solid #111; }

  /* 날짜·서명 */
  .sign-area { margin-top: 28px; }
  .sign-date { text-align: center; font-size: 14px; margin-bottom: 22px; letter-spacing: 1px; }
  .sign-row { display: flex; justify-content: space-between; gap: 20px; }
  .sign-block { flex: 1; border: 1px solid #bbb; padding: 14px 16px; min-height: 100px; }
  .sign-block .sign-label { font-size: 11px; font-weight: 700; margin-bottom: 8px; border-bottom: 1px solid #ddd; padding-bottom: 4px; }
  .sign-block .sign-name  { font-size: 13px; margin-bottom: 6px; }
  .sign-block .sign-img   { max-width: 160px; max-height: 60px; margin-top: 6px; }
  .sign-blank { border-bottom: 1px solid #555; width: 120px; display: inline-block; height: 18px; }

  /* 참고 박스 */
  .note-box {
    margin-top: 22px; padding: 10px 14px;
    border: 1px solid #ccc; border-radius: 2px; background: #fafafa;
    font-size: 11px; color: #555; line-height: 1.8;
  }
  .note-box li { list-style: disc; margin-left: 16px; }

  /* 인쇄 전용 */
  @media print {
    body { background: #fff; }
    .page { padding: 15mm 18mm; }
    .no-print { display: none !important; }
  }

  /* 화면 미리보기 버튼바 */
  .toolbar {
    position: fixed; top: 0; left: 0; right: 0; z-index: 100;
    background: #1e293b; color: #fff; padding: 10px 20px;
    display: flex; align-items: center; gap: 12px; font-size: 13px;
  }
  .toolbar h1 { font-size: 14px; font-weight: 700; flex: 1; }
  .btn-print {
    padding: 6px 16px; background: #7c3aed; color: #fff;
    border: none; border-radius: 4px; cursor: pointer; font-size: 12px; font-weight: 600;
  }
  .btn-close {
    padding: 6px 14px; background: #475569; color: #fff;
    border: none; border-radius: 4px; cursor: pointer; font-size: 12px;
  }
  @media print { .toolbar { display: none; } }
  body:has(.toolbar) .page { margin-top: 48px; }

  .auto-badge {
    display: inline-block; font-size: 10px; background: #fffbeb; color: #b45309;
    border: 1px solid #fcd34d; border-radius: 3px; padding: 1px 6px; margin-left: 6px;
    vertical-align: middle; font-weight: 600;
  }
  .signed-badge {
    display: inline-block; font-size: 10px; background: #f0fdf4; color: #166534;
    border: 1px solid #86efac; border-radius: 3px; padding: 1px 6px; margin-left: 6px;
    vertical-align: middle; font-weight: 600;
  }
</style>
</head>
<body>

{{-- 화면 미리보기 툴바 (인쇄 시 숨김) --}}
<div class="toolbar no-print">
  <h1>위임장 미리보기 — {{ $prescription->rx_number }}</h1>
  @if($isAutoGenerated)
    <span style="font-size:11px;background:#fffbeb;color:#b45309;padding:3px 10px;border-radius:3px;border:1px solid #fcd34d;">자동 생성 문서</span>
  @else
    <span style="font-size:11px;background:#f0fdf4;color:#166534;padding:3px 10px;border-radius:3px;border:1px solid #86efac;">서명 완료</span>
  @endif
  <button class="btn-print" onclick="window.print()">🖨 인쇄 / PDF 저장</button>
  <button class="btn-close" onclick="window.close()">닫기</button>
</div>

<div class="page">
  {{-- 제목 --}}
  <div class="doc-title">건 강 보 험 요 양 급 여 청 구 위 임 장</div>
  <div class="doc-sub">건강보험법 시행규칙 제22조에 의거 요양급여비용의 청구 및 수령을 위임합니다.</div>

  {{-- ① 위임인(환자) 정보 --}}
  <div class="section">
    <div class="section-title">① 위임인 (환자)</div>
    <table class="info-tbl">
      <tr>
        <td class="label">성 명</td>
        <td>{{ $patient->name ?? $prescription->patient_name_ocr ?? '—' }}</td>
        <td class="label">생년월일</td>
        <td>{{ $prescription->resident_no_ocr ? substr(preg_replace('/[^0-9]/','',$prescription->resident_no_ocr), 0, 6) : '—' }}</td>
      </tr>
      <tr>
        <td class="label">주민등록번호</td>
        <td colspan="3">
          {{ $prescription->resident_no_ocr
              ? (substr(preg_replace('/[^0-9]/','',$prescription->resident_no_ocr),0,6).' - '.substr(preg_replace('/[^0-9]/','',$prescription->resident_no_ocr),6,1).'●●●●●●')
              : '— — — — — —  -  ● ● ● ● ● ● ●' }}
        </td>
      </tr>
      <tr>
        <td class="label">주 소</td>
        <td colspan="3">{{ $patient->address ?? $prescription->address_ocr ?? '—' }}</td>
      </tr>
      <tr>
        <td class="label">연락처</td>
        <td>{{ $patient->mobile ?? $prescription->mobile_ocr ?? '—' }}</td>
        <td class="label">건강보험번호</td>
        <td>{{ $patient->health_insurance_no ?? '—' }}</td>
      </tr>
    </table>
  </div>

  {{-- ② 수임인(요양기관) 정보 --}}
  <div class="section">
    <div class="section-title">② 수임인 (요양기관)</div>
    <table class="info-tbl">
      <tr>
        <td class="label">기 관 명</td>
        <td>{{ config('nhis.institution.name', 'CE(씨이) 의료기기') }}</td>
        <td class="label">요양기관기호</td>
        <td>{{ config('nhis.institution.code', '—') }}</td>
      </tr>
      <tr>
        <td class="label">사업자번호</td>
        <td>{{ config('nhis.institution.biz_no') ?: config('popbill.company.corp_name', '—') }}</td>
        <td class="label">대 표 자</td>
        <td>{{ config('popbill.company.ceo_name', '—') }}</td>
      </tr>
      <tr>
        <td class="label">주 소</td>
        <td colspan="3">{{ config('popbill.company.addr', '—') }}</td>
      </tr>
      <tr>
        <td class="label">연락처</td>
        <td colspan="3">{{ config('popbill.company.tel', '—') }}</td>
      </tr>
    </table>
  </div>

  {{-- ③ 처방 정보 --}}
  <div class="section">
    <div class="section-title">③ 처방 정보</div>
    <table class="info-tbl">
      <tr>
        <td class="label">처방전 번호</td>
        <td>{{ $prescription->rx_number }}</td>
        <td class="label">처방 발행일</td>
        <td>{{ $prescription->issued_date?->format('Y년 m월 d일') ?? '—' }}</td>
      </tr>
      <tr>
        <td class="label">발행 의료기관</td>
        <td>{{ $prescription->hospital_name ?? '—' }}</td>
        <td class="label">담당 의사</td>
        <td>{{ $prescription->doctor_name ?? '—' }}</td>
      </tr>
      <tr>
        <td class="label">상병명(코드)</td>
        <td colspan="3">
          {{ $prescription->disease_name ?? '—' }}
          @if($prescription->disease_code) ({{ $prescription->disease_code }}) @endif
        </td>
      </tr>
      <tr>
        <td class="label">처방일수 / 총수량</td>
        <td colspan="3">
          {{ $prescription->total_days ? $prescription->total_days.'일' : '—' }}
          / {{ $prescription->total_count ? $prescription->total_count.'개' : '—' }}
        </td>
      </tr>
    </table>
  </div>

  {{-- ④ 위임 내용 --}}
  <div class="section">
    <div class="section-title">④ 위임 내용</div>
    <div class="content-box">
      본인 <b>{{ $patient->name ?? $prescription->patient_name_ocr ?? '위임인' }}</b>은(는)
      위의 수임인에게 상기 처방전에 의한
      <b>건강보험 요양급여비용의 청구 및 수령에 관한 일체의 권한</b>을 위임합니다.<br><br>
      위임 범위: 건강보험 급여 대상 보조기기(의료기기)의 급여비용 청구, 공단 부담금 수령,
      관련 서류 제출 및 기타 청구에 필요한 모든 행위
    </div>
  </div>

  {{-- 날짜 · 서명 --}}
  <div class="sign-area">
    <div class="sign-date">
      {{ now()->format('Y') }}년&nbsp;&nbsp;{{ now()->format('m') }}월&nbsp;&nbsp;{{ now()->format('d') }}일
    </div>
    <div class="sign-row">
      {{-- 위임인 서명 --}}
      <div class="sign-block">
        <div class="sign-label">
          위임인 서명
          @if($consent && $consent->status === 'agreed')
            <span class="signed-badge">전자서명 완료</span>
          @else
            <span class="auto-badge">서명 없음</span>
          @endif
        </div>
        <div class="sign-name">
          성명: {{ $patient->name ?? $prescription->patient_name_ocr ?? '—' }} (인)
        </div>
        @if($consent && $consent->status === 'agreed' && $consent->signature_data)
          <img src="{{ $consent->signature_data }}" class="sign-img" alt="전자서명">
        @else
          <div style="margin-top:16px;font-size:11px;color:#999;">(직접 서명 또는 날인)</div>
          <div style="margin-top:20px;border-bottom:1px solid #555;width:140px;">&nbsp;</div>
        @endif
      </div>

      {{-- 수임인 확인 --}}
      <div class="sign-block">
        <div class="sign-label">수임인 확인</div>
        <div class="sign-name">
          기관명: {{ config('nhis.institution.name', 'CE(씨이) 의료기기') }}
        </div>
        <div style="margin-top:6px;font-size:12px;">
          대 표: {{ config('popbill.company.ceo_name', '—') }} (인)
        </div>
        <div style="margin-top:20px;border-bottom:1px solid #555;width:140px;">&nbsp;</div>
      </div>
    </div>
  </div>

  {{-- 유의사항 --}}
  <div class="note-box">
    <ul>
      <li>본 위임장은 건강보험법 제47조 및 시행규칙 제22조에 근거하여 작성됩니다.</li>
      <li>위임 기간: 상기 처방전에 의한 급여비용 청구 완료 시까지</li>
      <li>위임인(환자)은 언제든지 본 위임을 철회할 수 있으며, 철회 시 수임인에게 서면으로 통보하여야 합니다.</li>
      <li>본 문서는 {{ $isAutoGenerated ? '시스템에 의해 자동 생성된 문서입니다.' : '환자의 전자서명이 포함된 문서입니다.' }}</li>
    </ul>
  </div>
</div>

</body>
</html>
